# Generated by Django 3.2.25 on 2024-05-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_default_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
