export STRIPE_PUBLIC_KEY='pk_test_51P0kUf2MqiGwcstyD64Y018QQ5qqwmalD1xTB42HuVvtjrVbwpbWVAPUSrBBVPW9gn9gY3KuBr1c5LRVvRkByfLD00AAdnayvj'
export STRIPE_SECRET_KEY='sk_test_51P0kUf2MqiGwcstyvOQTOeuzjX0nd9bb8cacnmETrBtTO4hFpufuZaJwsctZDlKcoO8N7wwgbZai6zEqaZACCPRI00Eeevn2pn'
export STRIPE_WH_SECRET=whsec_aThFbBbqfco1nXwJ7OoEqLeY9z18VQpk
export DATABASE_URL=postgres://tfgfvbtw:T2JUhI9DUpIq2NlujO33dxl9vx-YhpRx@tai.db.elephantsql.com/tfgfvbtw
export SECRET_KEY='django-insecure-dlp@@i(9=nz8$*uxme$+lzxt!k$+s@xx!so^q8d2j!y_u)!=v6'
export DEVELOPMENT=True