# Generated by Django 3.2.25 on 2024-04-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20240405_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
