# Generated by Django 4.2.11 on 2024-03-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(max_length=254)),
                ('size', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('X', 'X'), ('YouTube', 'YouTube'), ('Pinterest', 'Pinterest'), ('Snapchat', 'Snapchat'), ('Custom', 'Custom')], max_length=32)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designs.category')),
            ],
        ),
    ]
